sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
      - xvfb
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script: |
  set -e
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    npm run build:ci:dev
    sh ./scripts/release-ci.sh
  else
    npm run build:ci:pr
  fi;
branches:
  only:
  - /^[0-9]+\.[0-9]+$/
  - dev
env:
  global:
  - GH_REF: github.com/ractivejs/ractive.git
  - CDN_REF: github.com/ractivejs/cdn.ractivejs.org.git
  - secure: nlnXJW/imf/w6qdTd7UCpRqLhLioxU6fllJPbP1DZr/9rp44HNVSPNxxGrA808VDXQ1ccpXBxIV9mgIi4Q/G0FUILA5NsSGYdQE00A+Lw3qnvv5FQ7Qoux44BKYi4L1W+4Zi3NEr7TAL+/dHCAk5k/ZKLTCCxiziAEw3M+akE4A=
  - secure: W+gKWvHDgHXI+1tARD+QxFbgjxhU6AN9Fn40v4u5lNwjOXuxcgH6UMK9YaePPaFAO62H7EeUZdbeghn3qTixR6naUewdq+U50U814Y6gcXhAAHcPoHBkbUOUAuUWbp3saNcECOMUlLsiOl2S+A8iMvwEFqz84O2Pdwj68TmKJHw=
  - secure: iUqcSoWpThxocqJsoJAhbEZeQWibsM1V6PsQN9dGOS2DhaEcPaKg8yz7wL1V+rNKLzBPo9p41BPT6ij8SeVVMJ8lsvjJgptPItoPjeS9CQ9vzQ/aC/I+56mD86I7aMwkFciZXWVYYRPZ9u/5qaqUcsKyn6LVz41CZfFiJXCbm64=
  - secure: lx6U8QucHZnZQlF5qH4W+crc0ip05wCoFm+BAvJXuLHEtBjRQS1LWVEVJxKHBk7A9rm6fMEbAFo0unPCRiLNWpcfR+srzVlut+Ha+aQuQVI1dMyQZ+ngoi+s7BvL3pCH/Wp2RSTL2tkyCsVin0JVxYa6TAif1fyVa3P1BmVvdGw=
  - secure: "JOketNVw2TtrWUfIVVKZ3Fk1E5JFpcKYvLjr6bd8jizgQjIPj05ixC2K8MIFosqJ1Ri151KX1NG1JI0lTd1QPzwtKovPLu0qvbi89kj4BGvuo1F2tnFrm2SyoTTSDAvaD7HXs3ZdVNseOq1NAnZSso6TOU2XPZFe3jldr8MxF68="
